branches:
  - main
tagFormat: 'v${version}'

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: "RELEASE: v${nextRelease.version}"
  - "@semantic-release/github"
